# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impphotos.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_photosImp(object):
    def setupUi(self, photosImp):
        photosImp.setObjectName("photosImp")
        photosImp.setWindowModality(QtCore.Qt.ApplicationModal)
        photosImp.resize(381, 162)
        photosImp.setMinimumSize(QtCore.QSize(381, 162))
        photosImp.setMaximumSize(QtCore.QSize(381, 162))
        photosImp.setWhatsThis("")
        photosImp.setSizeGripEnabled(False)
        self.layoutWidget = QtWidgets.QWidget(photosImp)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.imp = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp.sizePolicy().hasHeightForWidth())
        self.imp.setSizePolicy(sizePolicy)
        self.imp.setObjectName("imp")
        self.gridLayout.addWidget(self.imp, 0, 2, 1, 1)
        self.toolButtonImport = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonImport.sizePolicy().hasHeightForWidth())
        self.toolButtonImport.setSizePolicy(sizePolicy)
        self.toolButtonImport.setObjectName("toolButtonImport")
        self.gridLayout.addWidget(self.toolButtonImport, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.out = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out.sizePolicy().hasHeightForWidth())
        self.out.setSizePolicy(sizePolicy)
        self.out.setObjectName("out")
        self.gridLayout.addWidget(self.out, 2, 2, 1, 1)
        self.toolButtonOut = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonOut.sizePolicy().hasHeightForWidth())
        self.toolButtonOut.setSizePolicy(sizePolicy)
        self.toolButtonOut.setObjectName("toolButtonOut")
        self.gridLayout.addWidget(self.toolButtonOut, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(photosImp)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 120, 181, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setObjectName("ok")
        self.horizontalLayout.addWidget(self.ok)
        self.closebutton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closebutton.sizePolicy().hasHeightForWidth())
        self.closebutton.setSizePolicy(sizePolicy)
        self.closebutton.setObjectName("closebutton")
        self.horizontalLayout.addWidget(self.closebutton)

        self.retranslateUi(photosImp)
        QtCore.QMetaObject.connectSlotsByName(photosImp)

    def retranslateUi(self, photosImp):
        _translate = QtCore.QCoreApplication.translate
        photosImp.setWindowTitle(_translate("photosImp", "ImportPhotos"))
        self.label.setText(_translate("photosImp", "Input folder location"))
        self.toolButtonImport.setText(_translate("photosImp", "Browse..."))
        self.label_2.setText(_translate("photosImp", "Output file location"))
        self.toolButtonOut.setText(_translate("photosImp", "Browse..."))
        self.ok.setText(_translate("photosImp", "OK"))
        self.closebutton.setText(_translate("photosImp", "Close"))

