# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'impphotos.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_photosImp(object):
    def setupUi(self, photosImp):
        photosImp.setObjectName("photosImp")
        photosImp.setWindowModality(QtCore.Qt.NonModal)
        photosImp.resize(815, 470)
        photosImp.setMinimumSize(QtCore.QSize(382, 223))
        photosImp.setWhatsThis("")
        photosImp.setSizeGripEnabled(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(photosImp)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(photosImp)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.closebutton = QtWidgets.QPushButton(photosImp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closebutton.sizePolicy().hasHeightForWidth())
        self.closebutton.setSizePolicy(sizePolicy)
        self.closebutton.setObjectName("closebutton")
        self.gridLayout.addWidget(self.closebutton, 7, 4, 1, 1)
        self.imp = QtWidgets.QLineEdit(photosImp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imp.sizePolicy().hasHeightForWidth())
        self.imp.setSizePolicy(sizePolicy)
        self.imp.setObjectName("imp")
        self.gridLayout.addWidget(self.imp, 0, 2, 1, 1)
        self.canvas_extent = QtWidgets.QCheckBox(photosImp)
        self.canvas_extent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.canvas_extent.setObjectName("canvas_extent")
        self.gridLayout.addWidget(self.canvas_extent, 5, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.ok = QtWidgets.QPushButton(photosImp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setObjectName("ok")
        self.horizontalLayout_2.addWidget(self.ok)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 4, 1, 1)
        self.toolButtonImport = QtWidgets.QPushButton(photosImp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonImport.sizePolicy().hasHeightForWidth())
        self.toolButtonImport.setSizePolicy(sizePolicy)
        self.toolButtonImport.setObjectName("toolButtonImport")
        self.gridLayout.addWidget(self.toolButtonImport, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(photosImp)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.toolButtonOut = QtWidgets.QPushButton(photosImp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonOut.sizePolicy().hasHeightForWidth())
        self.toolButtonOut.setSizePolicy(sizePolicy)
        self.toolButtonOut.setObjectName("toolButtonOut")
        self.gridLayout.addWidget(self.toolButtonOut, 2, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 6, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 3, 4, 1, 1)
        self.out = QtWidgets.QLineEdit(photosImp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out.sizePolicy().hasHeightForWidth())
        self.out.setSizePolicy(sizePolicy)
        self.out.setObjectName("out")
        self.gridLayout.addWidget(self.out, 2, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(photosImp)
        QtCore.QMetaObject.connectSlotsByName(photosImp)

    def retranslateUi(self, photosImp):
        _translate = QtCore.QCoreApplication.translate
        photosImp.setWindowTitle(_translate("photosImp", "ImportPhotos"))
        self.label.setText(_translate("photosImp", "Input folder location"))
        self.closebutton.setText(_translate("photosImp", "Close"))
        self.canvas_extent.setText(_translate("photosImp", "Only import photos in canvas extent"))
        self.ok.setText(_translate("photosImp", "OK"))
        self.toolButtonImport.setText(_translate("photosImp", "Browse..."))
        self.label_2.setText(_translate("photosImp", "Output file location"))
        self.toolButtonOut.setText(_translate("photosImp", "Browse..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    photosImp = QtWidgets.QDialog()
    ui = Ui_photosImp()
    ui.setupUi(photosImp)
    photosImp.show()
    sys.exit(app.exec_())

